services:
  postgres-db:
    image: postgres:18.3-alpine
    container_name: postgres-db
    env_file:
      - .env
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - pgdata:/var/lib/postgresql
    restart: unless-stopped

  aitracker_api:
    build:
      context: ./api
      dockerfile: Dockerfile
    image: aitracker_api
    container_name: aitracker_api
    env_file:
      - .env
    depends_on:
      - postgres-db
    restart: unless-stopped

  aitracker_dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    image: aitracker_dashboard
    container_name: aitracker_dashboard
    env_file:
      - .env
    depends_on:
      - aitracker_api
    restart: unless-stopped

  services:
  caddy:
    image: caddy:2
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - aitracker_dashboard
      - aitracker_api

volumes:
  pgdata:
  caddy_data:
  caddy_config: