events {
    worker_connections 1024;
}

http {
    server {
        listen 80;
        location /track {
            proxy_pass http://aitracker_api:3000/track;
        }

        location / {
            proxy_pass http://aitracker_dashboard:8000;
        }
    }
}
